config/routes.rb
Rails.application.routes.draw do
  # get 'home/zipcode'
  root 'home#index'
  
  post "zipcode" => "home#zipcode"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=89129&distance=0&API_KEY=3252A785-97FF-49BC-A35D-6BDA24B786A5'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    #Check for empty return results
    if @output.empty?
      @final_output = "Error"
    elsif !@output
      @final_output = "Error"
    else
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
        @api_color = "gray"
        @api_description = "Error"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "Good"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "Moderate"
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "USG"
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "Unhealthy"
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "Very Unhealthy"
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "magenta"
      @api_description = "Hazardous"
    end

  end

  def zipcode
    @zip_query = params[:zipcode]

    if params[:zipcode] == ""
      @zip_query = "Please enter a zipcode"
    elsif params[:zipcode]
      require 'net/http'
      require 'json'
      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode='+@zip_query+'&distance=0&API_KEY=3252A785-97FF-49BC-A35D-6BDA24B786A5'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
  
      #Check for empty return results
      if @output.empty?
        @final_output = "Error"
      elsif !@output
        @final_output = "Error"
      else
        @final_output = @output[0]['AQI']
      end
  
      if @final_output == "Error"
          @api_color = "gray"
          @api_description = "Error"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = "Good"
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = "Moderate"
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = "USG"
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = "Unhealthy"
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = "Very Unhealthy"
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "magenta"
        @api_description = "Hazardous"
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <div class="jumbotron <%= @api_color %>">
        <h1 class="display-4"><%= @final_output %></h1>
        <p class="lead">This is the current ozone air quality readout for my neighbourhood in Singapore.</p>
        <hr class="my-4">
        <p><%= @api_description %></p>
    </div>
  

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
    <h1 class="display-4"><%= @final_output %></h1>
    <p class="lead">This is the current ozone air quality readout for 
        <% if @zip_query != "Please enter a zipcode" %>
            <%= @zip_query %> zipcode.
        <% else %>
            <%= "Unknown Zipcode" %>
        <% end %> 
        .</p>
    <hr class="my-4">
    <p><%= @api_description %></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "My OZone!", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <%= form_tag zipcode_path, :method => 'POST' do %>
        <div class="d-flex">
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control me-2"  %>
        <%= submit_tag "Search", class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-2">
      <%= yield %>
    </div>
  </body>
</html>